### ISSUE TITLE
width of interface and usage of two potentials

### ISSUE THREAD

**Issue by bbuenim** [ksaaskil/shc-python-tools#10]
Dear. Kimmo

Thanks for your excellent research

I would like to change the length of the interface width to consider thick layer( > 10nm)

so, I changed the default width = 3.0 to 50.0 in the simulation.lmp

and i changed the width of xxx.py files in sdhc. 

but there is some problem to do it 

is it right method that I did it to calculate more thicker inteface?

How can I change the length of the width of interface. ?

and also

in the code, it looks like that only one potential looks being available.

Is it possible to use two or more potentials in complex system (e,g SiC+SiO , so there are two potentials used concurrently in single simulation for SiC.meam and SiO.tersoff )

Could you give me comments?

Thanks

**Comment by ksaaskil** [comment]
Hi,

> I would like to change the length of the interface width to consider thick layer( > 10nm)

I assume you want to expand the thickness because you have long-range interactions in the system, and you want to ensure that contributions from long-range forces to heat current are included. Indeed, the correct approach is to (1) modify the LAMMPS configuration file so that the velocities of of all atoms at the "interface" are dumped to a file, and (2) modify the heat current calculation file so that force constant matrix is computed for all the atoms. Note the caveat mentioned in the README:

_The logic how atom IDs are tracked throughtout the process is fragile. For example, the interface atoms are computed independently both when starting the LAMMPS simulation (to know which velocities to dump) and when calculating force constants afterwards. Currently these atom IDs must match._

> Is it possible to use two or more potentials in complex system

Yes it is possible, but you have to adapt the code for your own system. This repository is only an example. People have applied the method to various kinds of systems. The limitations are explained in the research paper. For example, in this repository, we assume that (1) atoms vibrate around static equilibrium points so that the first-order force expansion is valid and (2) long-range forces are accounted for. For example, if you had Coulomb forces in the system, it might be very difficult to account for those in the heat current. 

I hope this helps you forward, sorry for the delay in response.
