### ISSUE TITLE
shc run error

### ISSUE THREAD

**Issue by mostafav68** [ksaaskil/shc-python-tools#2]
hi
I just start working on your codes!
thanks for sharing it but it has a little documentation.
I run the sample code as mpirun -np 4 python silicon_example.py 
it ends up with the error
AttributeError: type object 'SHCPostProc' has no attribute 'SHCPostProc'

any ideas about what is going on?
thanks

**Comment by ksaaskil** [comment]
Hey, sorry for being late on this. I'm not sure what went wrong in your case but I have improved the example a lot since. I also doubt if you can `mpirun -np 4 python silicon_example.py`, AFAICS that would run four instances of the script in parallel which is not what you want. See [here](https://lammps.sandia.gov/doc/Python_mpi.html) how to run LAMMPS in parallel from Python.
